// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from '/Users/bobochang/Documents/PROJECTS/chang-generator/chang-generator-web-frontend/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import PlusOutlined from '/Users/bobochang/Documents/PROJECTS/chang-generator/chang-generator-web-frontend/node_modules/@ant-design/icons/es/icons/PlusOutlined';
import CrownOutlined from '/Users/bobochang/Documents/PROJECTS/chang-generator/chang-generator-web-frontend/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from '/Users/bobochang/Documents/PROJECTS/chang-generator/chang-generator-web-frontend/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { HomeOutlined, PlusOutlined, CrownOutlined, TableOutlined };
